version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anatolii_tsiko
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "3010:3000"
    depends_on:
      - mongo
    networks:
      - nginx_proxy
      - db_network
  mongo:
    container_name: anatolii_tsiko_mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27015:27017"
    networks:
      - db_network

networks:
  db_network:
    internal: true
  nginx_proxy:
    external: true